# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest
    environment: 
      name: CI Workflow

    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Clean Install
        run: npm ci
      - name: Build
        run: npm run build:release --if-present
